image: adoptopenjdk:8

stages:
  - build

  - docker

  - deploy
  
build:
  stage: build
  script:
    ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar


docker:
  stage: docker
  image: docker:latest
  needs:
    - build
  
  services:
    - docker:dind
  before_script:
    - docker info
    - echo $CI_BUILD_TOKEN | docker login -u "$CI_REGISTRY_USER" -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_USER/am-autos-api:latest .
    - docker push $CI_REGISTRY_USER/am-autos-api:latest

deploy:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    #                        App name from prev step  Key from your heroku account
    - dpl --provider=heroku --app=am-autos-api --api-key=$HEROKU_API_KEY
  only: # Heroku will ONLY deploy from main or master branch!
    - main
