image: adoptopenjdk:8

stages:
  - build
  - test
  - docker
  - codeCoverage
  - deploy
  
build:
  stage: build
  script:
    ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
test:
  stage: test
  script:
    ./gradlew test
  artifacts:
    paths:
      - build/test-results/test/TEST*.xml
docker:
  stage: docker
  image: docker:latest
  needs:
    - build
    - test
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    - docker build -t am-autos-api .
  artifacts:
    image: temp

codeCoverage:
  image: adoptopenjdk:8
  needs: 
    - build
    - test
  stage: codeCoverage
  script:
    - ./gradlew jacocoTestReport
    - ./gradlew jacocoTestCoverageVerification
  allow_failure: true
  artifacts: 
    when: always
    paths:
      - build/reports/jacoco/
deploy:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    #                        App name from prev step  Key from your heroku account
    - dpl --provider=heroku --app=am-autos-api --api-key=$HEROKU_API_KEY
  only: # Heroku will ONLY deploy from main or master branch!
    - main
