apiVersion: v1
kind: Service
metadata:
  name: andy-monica-autos-lb
spec:
  type: LoadBalancer
  selector:
    app: andy-monica-autos
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http